### ISSUE TITLE
没安装下来啊

### ISSUE THREAD

**Issue by Seven0711** [dzy321/file-upload#1]
如题，我在命令行窗口运行 `npm install koa2-image-upload --save` 得到如下结果<br>
![wx_20170627163356](https://user-images.githubusercontent.com/9974342/27578377-803484c2-5b56-11e7-835d-c76bf9ea0968.png)  
是我哪里搞错了吗？

**Comment by dzy321** [comment]
npm i koa2-file-upload，文档我已经改了
